import random
themes = [
    "wisdom",
    "dreams", 
    "time",
    "light",
    "shadows",
    "hope",
    "destiny",
    "silence",
    "freedom", 
    "mystery",
    'Indian',
    'Mythology',
    'Greek',
    'Retro',
    'Retro-Cyber'
    "Retro-Cyber",
    "Retro-Futurism",
    "Retro-Tech",
    "Retro-SciFi",
    "Retro-Robotics",
    "Retro-Machines",
    "Retro-Neon",
    "Retro-Space",
    "Retro-Digital",
    "Retro-Nano",
    "Retro-Synthwave",
    "Retro-Dreamwave",
    "Retro-Vaporwave",
    "Retro-Chillwave",
    "Retro-Darkwave",
    "Retro-Glowwave",
    "Retro-Arcadewave",
    "Retro-Dreamscape",
    "Retro-Laserwave",
    "Retro-Arcade",
    "Retro-Pixel",
    "Retro-8bit",
    "Retro-Console",
    "Retro-Glitch",
    "Retro-VR",
    "Retro-Quest",
    "Retro-Hologram",
    "Retro-Neonpunk",
    "Retro-Cyberpunk",
    "Retro-Biopunk",
    "Retro-Steampunk",
    "Retro-Technoir",
    "Retro-Shadowpunk",
    "Retro-Cyberscape",
    "Retro-Dystopia"
]
chosen_theme = random.choice(themes)
def x():
    return chosen_theme